
export const ColorsHsl = {
  GRAYSCALE_HUE: "204",
  BLACK_HSL: "var(--grayscale-hue),24%,8%",
  DARK_GRAY1_HSL: "var(--grayscale-hue),23%,12%",
  DARK_GRAY2_HSL: "var(--grayscale-hue),23%,16%",
  DARK_GRAY3_HSL: "var(--grayscale-hue),23%,21%",
  DARK_GRAY4_HSL: "var(--grayscale-hue),23%,25%",
  DARK_GRAY5_HSL: "var(--grayscale-hue),22%,29%",
  GRAY1_HSL: "var(--grayscale-hue),16%,43%",
  GRAY2_HSL: "var(--grayscale-hue),13%,52%",
  GRAY3_HSL: "var(--grayscale-hue),15%,60%",
  GRAY4_HSL: "var(--grayscale-hue),18%,71%",
  GRAY5_HSL: "var(--grayscale-hue),22%,79%",
  LIGHT_GRAY1_HSL: "var(--grayscale-hue),22%,84%",
  LIGHT_GRAY2_HSL: "var(--grayscale-hue),26%,88%",
  LIGHT_GRAY3_HSL: "var(--grayscale-hue),25%,91%",
  LIGHT_GRAY4_HSL: "var(--grayscale-hue),33%,94%",
  LIGHT_GRAY5_HSL: "var(--grayscale-hue),33%,97%",
  WHITE_HSL: "var(--grayscale-hue),0%,100%",
  VERMILION_HUE: "12",
  VERMILION1_HSL: "var(--vermilion-hue),84%,34%",
  VERMILION2_HSL: "var(--vermilion-hue),83%,39%",
  VERMILION3_HSL: "var(--vermilion-hue),83%,45%",
  VERMILION4_HSL: "var(--vermilion-hue),83%,55%",
  VERMILION5_HSL: "var(--vermilion-hue),100%,65%",
  RED_HUE: "0",
  RED1_HSL: "var(--red-hue),60%,41%",
  RED2_HSL: "var(--red-hue),60%,47%",
  RED3_HSL: "var(--red-hue),69%,54%",
  RED4_HSL: "var(--red-hue),89%,65%",
  RED5_HSL: "var(--red-hue),100%,73%",
  ROSE_HUE: "337",
  ROSE1_HSL: "var(--rose-hue),66%,40%",
  ROSE2_HSL: "var(--rose-hue),67%,46%",
  ROSE3_HSL: "var(--rose-hue),71%,52%",
  ROSE4_HSL: "var(--rose-hue),90%,62%",
  ROSE5_HSL: "var(--rose-hue),100%,70%",
  VIOLET_HUE: "300",
  VIOLET1_HSL: "var(--violet-hue),43%,25%",
  VIOLET2_HSL: "var(--violet-hue),43%,32%",
  VIOLET3_HSL: "var(--violet-hue),43%,39%",
  VIOLET4_HSL: "var(--violet-hue),33%,49%",
  VIOLET5_HSL: "var(--violet-hue),39%,61%",
  INDIGO_HUE: "252",
  INDIGO1_HSL: "var(--indigo-hue),43%,45%",
  INDIGO2_HSL: "var(--indigo-hue),47%,53%",
  INDIGO3_HSL: "var(--indigo-hue),63%,60%",
  INDIGO4_HSL: "var(--indigo-hue),82%,71%",
  INDIGO5_HSL: "var(--indigo-hue),100%,80%",
  COBALT_HUE: "218",
  COBALT1_HSL: "var(--cobalt-hue),66%,36%",
  COBALT2_HSL: "var(--cobalt-hue),67%,42%",
  COBALT3_HSL: "var(--cobalt-hue),67%,48%",
  COBALT4_HSL: "var(--cobalt-hue),76%,59%",
  COBALT5_HSL: "var(--cobalt-hue),100%,70%",
  BLUE_HUE: "203",
  BLUE1_HSL: "var(--blue-hue),82%,30%",
  BLUE2_HSL: "var(--blue-hue),82%,35%",
  BLUE3_HSL: "var(--blue-hue),82%,41%",
  BLUE4_HSL: "var(--blue-hue),68%,50%",
  BLUE5_HSL: "var(--blue-hue),85%,61%",
  TURQUOISE_HUE: "175",
  TURQUOISE1_HSL: "var(--turquoise-hue),100%,25%",
  TURQUOISE2_HSL: "var(--turquoise-hue),100%,30%",
  TURQUOISE3_HSL: "var(--turquoise-hue),100%,35%",
  TURQUOISE4_HSL: "var(--turquoise-hue),82%,44%",
  TURQUOISE5_HSL: "var(--turquoise-hue),79%,54%",
  GREEN_HUE: "155",
  GREEN1_HSL: "var(--green-hue),82%,22%",
  GREEN2_HSL: "var(--green-hue),82%,28%",
  GREEN3_HSL: "var(--green-hue),82%,33%",
  GREEN4_HSL: "var(--green-hue),79%,39%",
  GREEN5_HSL: "var(--green-hue),58%,52%",
  FOREST_HUE: "125",
  FOREST1_HSL: "var(--forest-hue),60%,28%",
  FOREST2_HSL: "var(--forest-hue),60%,34%",
  FOREST3_HSL: "var(--forest-hue),60%,41%",
  FOREST4_HSL: "var(--forest-hue),49%,51%",
  FOREST5_HSL: "var(--forest-hue),61%,62%",
  LIME_HUE: "75",
  LIME1_HSL: "var(--lime-hue),60%,34%",
  LIME2_HSL: "var(--lime-hue),60%,41%",
  LIME3_HSL: "var(--lime-hue),60%,47%",
  LIME4_HSL: "var(--lime-hue),65%,57%",
  LIME5_HSL: "var(--lime-hue),84%,69%",
  GOLD_HUE: "43",
  GOLD1_HSL: "var(--gold-hue),91%,34%",
  GOLD2_HSL: "var(--gold-hue),90%,39%",
  GOLD3_HSL: "var(--gold-hue),90%,45%",
  GOLD4_HSL: "var(--gold-hue),89%,55%",
  GOLD5_HSL: "var(--gold-hue),100%,63%",
  ORANGE_HUE: "30",
  ORANGE1_HSL: "var(--orange-hue),67%,39%",
  ORANGE2_HSL: "var(--orange-hue),67%,45%",
  ORANGE3_HSL: "var(--orange-hue),70%,51%",
  ORANGE4_HSL: "var(--orange-hue),87%,62%",
  ORANGE5_HSL: "var(--orange-hue),100%,70%",
  SEPIA_HUE: "30",
  SEPIA1_HSL: "var(--sepia-hue),53%,25%",
  SEPIA2_HSL: "var(--sepia-hue),54%,32%",
  SEPIA3_HSL: "var(--sepia-hue),54%,38%",
  SEPIA4_HSL: "var(--sepia-hue),43%,48%",
  SEPIA5_HSL: "var(--sepia-hue),48%,59%"
};

export const Colors = {
  BLACK: "hsl(var(--black-hsl))",
  DARK_GRAY1: "hsl(var(--dark-gray1-hsl))",
  DARK_GRAY2: "hsl(var(--dark-gray2-hsl))",
  DARK_GRAY3: "hsl(var(--dark-gray3-hsl))",
  DARK_GRAY4: "hsl(var(--dark-gray4-hsl))",
  DARK_GRAY5: "hsl(var(--dark-gray5-hsl))",
  GRAY1: "hsl(var(--gray1-hsl))",
  GRAY2: "hsl(var(--gray2-hsl))",
  GRAY3: "hsl(var(--gray3-hsl))",
  GRAY4: "hsl(var(--gray4-hsl))",
  GRAY5: "hsl(var(--gray5-hsl))",
  LIGHT_GRAY1: "hsl(var(--light-gray1-hsl))",
  LIGHT_GRAY2: "hsl(var(--light-gray2-hsl))",
  LIGHT_GRAY3: "hsl(var(--light-gray3-hsl))",
  LIGHT_GRAY4: "hsl(var(--light-gray4-hsl))",
  LIGHT_GRAY5: "hsl(var(--light-gray5-hsl))",
  WHITE: "hsl(var(--white-hsl))",
  VERMILION1: "hsl(var(--vermilion1-hsl))",
  VERMILION2: "hsl(var(--vermilion2-hsl))",
  VERMILION3: "hsl(var(--vermilion3-hsl))",
  VERMILION4: "hsl(var(--vermilion4-hsl))",
  VERMILION5: "hsl(var(--vermilion5-hsl))",
  RED1: "hsl(var(--red1-hsl))",
  RED2: "hsl(var(--red2-hsl))",
  RED3: "hsl(var(--red3-hsl))",
  RED4: "hsl(var(--red4-hsl))",
  RED5: "hsl(var(--red5-hsl))",
  ROSE1: "hsl(var(--rose1-hsl))",
  ROSE2: "hsl(var(--rose2-hsl))",
  ROSE3: "hsl(var(--rose3-hsl))",
  ROSE4: "hsl(var(--rose4-hsl))",
  ROSE5: "hsl(var(--rose5-hsl))",
  VIOLET1: "hsl(var(--violet1-hsl))",
  VIOLET2: "hsl(var(--violet2-hsl))",
  VIOLET3: "hsl(var(--violet3-hsl))",
  VIOLET4: "hsl(var(--violet4-hsl))",
  VIOLET5: "hsl(var(--violet5-hsl))",
  INDIGO1: "hsl(var(--indigo1-hsl))",
  INDIGO2: "hsl(var(--indigo2-hsl))",
  INDIGO3: "hsl(var(--indigo3-hsl))",
  INDIGO4: "hsl(var(--indigo4-hsl))",
  INDIGO5: "hsl(var(--indigo5-hsl))",
  COBALT1: "hsl(var(--cobalt1-hsl))",
  COBALT2: "hsl(var(--cobalt2-hsl))",
  COBALT3: "hsl(var(--cobalt3-hsl))",
  COBALT4: "hsl(var(--cobalt4-hsl))",
  COBALT5: "hsl(var(--cobalt5-hsl))",
  BLUE1: "hsl(var(--blue1-hsl))",
  BLUE2: "hsl(var(--blue2-hsl))",
  BLUE3: "hsl(var(--blue3-hsl))",
  BLUE4: "hsl(var(--blue4-hsl))",
  BLUE5: "hsl(var(--blue5-hsl))",
  TURQUOISE1: "hsl(var(--turquoise1-hsl))",
  TURQUOISE2: "hsl(var(--turquoise2-hsl))",
  TURQUOISE3: "hsl(var(--turquoise3-hsl))",
  TURQUOISE4: "hsl(var(--turquoise4-hsl))",
  TURQUOISE5: "hsl(var(--turquoise5-hsl))",
  GREEN1: "hsl(var(--green1-hsl))",
  GREEN2: "hsl(var(--green2-hsl))",
  GREEN3: "hsl(var(--green3-hsl))",
  GREEN4: "hsl(var(--green4-hsl))",
  GREEN5: "hsl(var(--green5-hsl))",
  FOREST1: "hsl(var(--forest1-hsl))",
  FOREST2: "hsl(var(--forest2-hsl))",
  FOREST3: "hsl(var(--forest3-hsl))",
  FOREST4: "hsl(var(--forest4-hsl))",
  FOREST5: "hsl(var(--forest5-hsl))",
  LIME1: "hsl(var(--lime1-hsl))",
  LIME2: "hsl(var(--lime2-hsl))",
  LIME3: "hsl(var(--lime3-hsl))",
  LIME4: "hsl(var(--lime4-hsl))",
  LIME5: "hsl(var(--lime5-hsl))",
  GOLD1: "hsl(var(--gold1-hsl))",
  GOLD2: "hsl(var(--gold2-hsl))",
  GOLD3: "hsl(var(--gold3-hsl))",
  GOLD4: "hsl(var(--gold4-hsl))",
  GOLD5: "hsl(var(--gold5-hsl))",
  ORANGE1: "hsl(var(--orange1-hsl))",
  ORANGE2: "hsl(var(--orange2-hsl))",
  ORANGE3: "hsl(var(--orange3-hsl))",
  ORANGE4: "hsl(var(--orange4-hsl))",
  ORANGE5: "hsl(var(--orange5-hsl))",
  SEPIA1: "hsl(var(--sepia1-hsl))",
  SEPIA2: "hsl(var(--sepia2-hsl))",
  SEPIA3: "hsl(var(--sepia3-hsl))",
  SEPIA4: "hsl(var(--sepia4-hsl))",
  SEPIA5: "hsl(var(--sepia5-hsl))"
};

export const IntentColors = {
  PT_INTENT_PRIMARY_HUE: "var(--blue-hue)",
  PT_INTENT_PRIMARY_HSL: "var(--blue3-hsl)",
  PT_INTENT_PRIMARY_HOVER_HSL: "var(--blue2-hsl)",
  PT_INTENT_PRIMARY_ACTIVE_HSL: "var(--blue1-hsl)",
  PT_INTENT_PRIMARY_TEXT_COLOR_HSL: "var(--blue2-hsl)",
  PT_DARK_INTENT_PRIMARY_TEXT_COLOR_HSL: "var(--blue5-hsl)",
  PT_INTENT_SUCCESS_HUE: "var(--green-hue)",
  PT_INTENT_SUCCESS_HSL: "var(--green3-hsl)",
  PT_INTENT_SUCCESS_HOVER_HSL: "var(--green2-hsl)",
  PT_INTENT_SUCCESS_ACTIVE_HSL: "var(--green1-hsl)",
  PT_INTENT_SUCCESS_TEXT_COLOR_HSL: "var(--green2-hsl)",
  PT_DARK_INTENT_SUCCESS_TEXT_COLOR_HSL: "var(--green5-hsl)",
  PT_INTENT_WARNING_HUE: "var(--orange-hue)",
  PT_INTENT_WARNING_HSL: "var(--orange3-hsl)",
  PT_INTENT_WARNING_HOVER_HSL: "var(--orange2-hsl)",
  PT_INTENT_WARNING_ACTIVE_HSL: "var(--orange1-hsl)",
  PT_INTENT_WARNING_TEXT_COLOR_HSL: "var(--orange2-hsl)",
  PT_DARK_INTENT_WARNING_TEXT_COLOR_HSL: "var(--orange5-hsl)",
  PT_INTENT_DANGER_HUE: "var(--red-hue)",
  PT_INTENT_DANGER_HSL: "var(--red3-hsl)",
  PT_INTENT_DANGER_HOVER_HSL: "var(--red2-hsl)",
  PT_INTENT_DANGER_ACTIVE_HSL: "var(--red1-hsl)",
  PT_INTENT_DANGER_TEXT_COLOR_HSL: "var(--red2-hsl)",
  PT_DARK_INTENT_DANGER_TEXT_COLOR_HSL: "var(--red5-hsl)"
};

export const LayoutColors = {
  PT_APP_BACKGROUND_COLOR: "var(--light-gray5)",
  PT_DARK_APP_BACKGROUND_COLOR: "var(--dark-gray3)",
  PT_APP_TOP_BACKGROUND_COLOR: "var(--white)",
  PT_DARK_APP_TOP_BACKGROUND_COLOR: "var(--dark-gray4)",
  PT_DIVIDER_BLACK: "hsla(var(--black-hsl),0.15)",
  PT_DARK_DIVIDER_BLACK: "hsla(var(--black-hsl),0.4)",
  PT_DARK_DIVIDER_WHITE: "hsla(var(--white-hsl),0.15)",
  PT_OUTLINE_COLOR: "hsla(var(--pt-intent-primary-hsl),0.6)",
  PT_DISABLED_OPACITY: "0.3"
};

export const TextColors = {
  PT_TEXT_COLOR: "var(--dark-gray1)",
  PT_TEXT_COLOR_MUTED: "var(--gray1)",
  PT_TEXT_COLOR_DISABLED: "hsla(var(--black-hsl),var(--pt-disabled-opacity))",
  PT_HEADING_COLOR: "var(--pt-text-color)",
  PT_LINK_COLOR: "var(--pt-intent-primary-text-color)",
  PT_DARK_TEXT_COLOR: "var(--light-gray5)",
  PT_DARK_TEXT_COLOR_MUTED: "var(--gray4)",
  PT_DARK_TEXT_COLOR_DISABLED: "hsla(var(--white-hsl),var(--pt-disabled-opacity))",
  PT_DARK_HEADING_COLOR: "var(--pt-dark-text-color)",
  PT_DARK_LINK_COLOR: "var(--pt-dark-intent-primary-text-color)",
  PT_TEXT_SELECTION_COLOR: "hsla(var(--blue-hue),100%,75%,0.6)",
  PT_CODE_TEXT_COLOR: "var(--pt-text-color-muted)",
  PT_DARK_CODE_TEXT_COLOR: "var(--pt-dark-text-color-muted)",
  PT_CODE_BACKGROUND_COLOR: "hsla(var(--white-hsl),0.7)",
  PT_DARK_CODE_BACKGROUND_COLOR: "hsla(var(--black-hsl),0.3)"
};

export const IconColors = {
  PT_ICON_COLOR: "var(--pt-text-color-muted)",
  PT_ICON_COLOR_HOVER: "var(--pt-text-color)",
  PT_ICON_COLOR_DISABLED: "var(--pt-text-color-disabled)",
  PT_ICON_COLOR_SELECTED: "var(--pt-intent-primary)",
  PT_DARK_ICON_COLOR: "var(--pt-dark-text-color-muted)",
  PT_DARK_ICON_COLOR_HOVER: "var(--pt-dark-text-color)",
  PT_DARK_ICON_COLOR_DISABLED: "var(--pt-dark-text-color-disabled)",
  PT_DARK_ICON_COLOR_SELECTED: "var(--pt-intent-primary)",
  PT_INTENT_PRIMARY: "hsl(var(--pt-intent-primary-hsl))",
  PT_INTENT_PRIMARY_HOVER: "hsl(var(--pt-intent-primary-hover-hsl))",
  PT_INTENT_PRIMARY_ACTIVE: "hsl(var(--pt-intent-primary-active-hsl))",
  PT_INTENT_PRIMARY_TEXT_COLOR: "hsl(var(--pt-intent-primary-text-color-hsl))",
  PT_DARK_INTENT_PRIMARY_TEXT_COLOR: "hsl(var(--pt-dark-intent-primary-text-color-hsl))",
  PT_INTENT_SUCCESS: "hsl(var(--pt-intent-success-hsl))",
  PT_INTENT_SUCCESS_HOVER: "hsl(var(--pt-intent-success-hover-hsl))",
  PT_INTENT_SUCCESS_ACTIVE: "hsl(var(--pt-intent-success-active-hsl))",
  PT_INTENT_SUCCESS_TEXT_COLOR: "hsl(var(--pt-intent-success-text-color-hsl))",
  PT_DARK_INTENT_SUCCESS_TEXT_COLOR: "hsl(var(--pt-dark-intent-success-text-color-hsl))",
  PT_INTENT_WARNING: "hsl(var(--pt-intent-warning-hsl))",
  PT_INTENT_WARNING_HOVER: "hsl(var(--pt-intent-warning-hover-hsl))",
  PT_INTENT_WARNING_ACTIVE: "hsl(var(--pt-intent-warning-active-hsl))",
  PT_INTENT_WARNING_TEXT_COLOR: "hsl(var(--pt-intent-warning-text-color-hsl))",
  PT_DARK_INTENT_WARNING_TEXT_COLOR: "hsl(var(--pt-dark-intent-warning-text-color-hsl))",
  PT_INTENT_DANGER: "hsl(var(--pt-intent-danger-hsl))",
  PT_INTENT_DANGER_HOVER: "hsl(var(--pt-intent-danger-hover-hsl))",
  PT_INTENT_DANGER_ACTIVE: "hsl(var(--pt-intent-danger-active-hsl))",
  PT_INTENT_DANGER_TEXT_COLOR: "hsl(var(--pt-intent-danger-text-color-hsl))",
  PT_DARK_INTENT_DANGER_TEXT_COLOR: "hsl(var(--pt-dark-intent-danger-text-color-hsl))",
  PT_FONT_FAMILY: "-apple-system,\"BlinkMacSystemFont\",\"Segoe UI\",\"Roboto\",\"Oxygen\",\"Ubuntu\",\"Cantarell\",\"Open Sans\",\"Helvetica Neue\",\"Icons16\",sans-serif",
  PT_FONT_FAMILY_MONOSPACE: "Consolas,Menlo,monospace",
  PT_BORDER_RADIUS: "3px",
  PT_ICON_SIZE_STANDARD: "16px",
  PT_ICON_SIZE_LARGE: "20px",
  PT_BORDER_SHADOW_OPACITY: "0.1",
  PT_DROP_SHADOW_OPACITY: "0.2",
  PT_DARK_BORDER_SHADOW_OPACITY: "0.2",
  PT_DARK_DROP_SHADOW_OPACITY: "0.4",
  PT_SHADOW_COLOR_HSL: "var(--black-hsl)",
  PT_DARK_SHADOW_COLOR_HSL: "var(--pt-shadow-color-hsl)",
  PT_ELEVATION_SHADOW_0: "0 0 0 1px var(--pt-divider-black),0 0 0 hsla(var(--pt-shadow-color-hsl),0),0 0 0 hsla(var(--pt-shadow-color-hsl),0)",
  PT_ELEVATION_SHADOW_1: "0 0 0 1px hsla(var(--pt-shadow-color-hsl),var(--pt-border-shadow-opacity)),0 0 0 hsla(var(--pt-shadow-color-hsl),0),0 1px 1px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity))",
  PT_ELEVATION_SHADOW_2: "0 0 0 1px hsla(var(--pt-shadow-color-hsl),var(--pt-border-shadow-opacity)),0 1px 1px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity)),0 2px 6px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity))",
  PT_ELEVATION_SHADOW_3: "0 0 0 1px hsla(var(--pt-shadow-color-hsl),var(--pt-border-shadow-opacity)),0 2px 4px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity)),0 8px 24px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity))",
  PT_ELEVATION_SHADOW_4: "0 0 0 1px hsla(var(--pt-shadow-color-hsl),var(--pt-border-shadow-opacity)),0 4px 8px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity)),0 18px 46px 6px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity))",
  PT_DARK_ELEVATION_SHADOW_0: "0 0 0 1px var(--pt-dark-shadow-color-hsl),0 0 0 hsla(var(--pt-dark-shadow-color-hsl),0),0 0 0 hsla(var(--pt-dark-shadow-color-hsl),0)",
  PT_DARK_ELEVATION_SHADOW_1: "0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-border-shadow-opacity)),0 0 0 hsla(var(--pt-dark-shadow-color-hsl),0),0 1px 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity))",
  PT_DARK_ELEVATION_SHADOW_2: "0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-border-shadow-opacity)),0 1px 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity)),0 2px 6px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity))",
  PT_DARK_ELEVATION_SHADOW_3: "0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-border-shadow-opacity)),0 2px 4px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity)),0 8px 24px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity))",
  PT_DARK_ELEVATION_SHADOW_4: "0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-border-shadow-opacity)),0 4px 8px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity)),0 18px 46px 6px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity))",
  PT_TRANSITION_EASE: "cubic-bezier(0.4,1,0.75,0.9)",
  PT_TRANSITION_EASE_BOUNCE: "cubic-bezier(0.54,1.12,0.38,1.11)",
  PT_INPUT_BOX_SHADOW: "inset 0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),0.15),inset 0 1px 1px hsla(var(--black-hsl),var(--pt-drop-shadow-opacity))",
  PT_DIALOG_BOX_SHADOW: "var(--pt-elevation-shadow-4)",
  PT_POPOVER_BOX_SHADOW: "var(--pt-elevation-shadow-3)",
  PT_TOOLTIP_BOX_SHADOW: "var(--pt-popover-box-shadow)",
  PT_DARK_INPUT_BOX_SHADOW: "inset 0 0 0 1px hsla(var(--pt-dark-shadow-color-hsl),0.3),inset 0 1px 1px hsla(var(--pt-dark-shadow-color-hsl),var(--pt-dark-drop-shadow-opacity))",
  PT_DARK_DIALOG_BOX_SHADOW: "var(--pt-dark-elevation-shadow-4)",
  PT_DARK_POPOVER_BOX_SHADOW: "var(--pt-dark-elevation-shadow-3)",
  PT_DARK_TOOLTIP_BOX_SHADOW: "var(--pt-dark-popover-box-shadow)"
};

export const Components = {
  BUTTON_BORDER_WIDTH: "1px",
  BUTTON_BOX_SHADOW: "inset 0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.2),inset 0 var(--button-border-width) 0 hsla(var(--pt-shadow-color-hsl),0.1)",
  BUTTON_BOX_SHADOW_ACTIVE: "inset 0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.2),inset 0 1px 2px hsla(var(--pt-shadow-color-hsl),0.2)",
  BUTTON_INTENT_BOX_SHADOW: "inset 0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.4),inset 0 var(--button-border-width) 0 hsla(var(--pt-shadow-color-hsl),0.2)",
  BUTTON_INTENT_BOX_SHADOW_ACTIVE: "inset 0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.4),inset 0 1px 2px hsla(var(--pt-shadow-color-hsl),0.2)",
  BUTTON_BOX_SHADOW_OVERLAY: "0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.2),0 1px 1px hsla(var(--pt-shadow-color-hsl),0.2)",
  BUTTON_BOX_SHADOW_OVERLAY_ACTIVE: "0 0 0 var(--button-border-width) hsla(var(--pt-shadow-color-hsl),0.2),inset 0 1px 1px hsla(var(--pt-shadow-color-hsl),0.1)",
  DARK_BUTTON_BOX_SHADOW: "0 0 0 var(--button-border-width) hsla(var(--pt-dark-shadow-color-hsl),0.4)",
  DARK_BUTTON_BOX_SHADOW_ACTIVE: "0 0 0 var(--button-border-width) hsla(var(--pt-dark-shadow-color-hsl),0.6),inset 0 1px 2px hsla(var(--pt-dark-shadow-color-hsl),0.2)",
  DARK_BUTTON_INTENT_BOX_SHADOW: "0 0 0 var(--button-border-width) hsla(var(--pt-dark-shadow-color-hsl),0.4)",
  DARK_BUTTON_INTENT_BOX_SHADOW_ACTIVE: "0 0 0 var(--button-border-width) hsla(var(--pt-dark-shadow-color-hsl),0.4),inset 0 1px 2px hsla(var(--pt-dark-shadow-color-hsl),0.2)",
  SHINE_COLOR_HSL: "var(--white-hsl)",
  SHINE_OPACITY: "0.8",
  SHINE_INTENT_COLOR_HSL: "var(--shine-color-hsl)",
  SHINE_INTENT_OPACITY: "0.1",
  DARK_SHINE_COLOR_HSL: "var(--shine-color-hsl)",
  DARK_SHINE_OPACITY: "0.05",
  BUTTON_GRADIENT: "linear-gradient(180deg,hsla(var(--shine-color-hsl),var(--shine-opacity)),hsla(var(--shine-color-hsl),0))",
  BUTTON_INTENT_GRADIENT: "linear-gradient(180deg,hsla(var(--shine-intent-color-hsl),var(--shine-intent-opacity)),hsla(var(--shine-intent-color-hsl),0))",
  DARK_BUTTON_GRADIENT: "linear-gradient(180deg,hsla(var(--dark-shine-color-hsl),var(--dark-shine-opacity)),hsla(var(--dark-shine-color-hsl),0))",
  BUTTON_COLOR_DISABLED: "var(--pt-text-color-disabled)",
  BUTTON_BACKGROUND_COLOR: "var(--light-gray5)",
  BUTTON_BACKGROUND_COLOR_HOVER: "var(--light-gray4)",
  BUTTON_BACKGROUND_COLOR_ACTIVE: "var(--light-gray2)",
  BUTTON_BACKGROUND_COLOR_DISABLED: "hsla(var(--light-gray1-hsl),0.5)",
  BUTTON_BACKGROUND_COLOR_ACTIVE_DISABLED: "hsla(var(--light-gray1-hsl),0.7)",
  BUTTON_INTENT_COLOR_DISABLED: "hsla(var(--white-hsl),0.6)",
  DARK_BUTTON_COLOR_DISABLED: "var(--pt-dark-text-color-disabled)",
  DARK_BUTTON_BACKGROUND_COLOR: "var(--dark-gray5)",
  DARK_BUTTON_BACKGROUND_COLOR_HOVER: "var(--dark-gray4)",
  DARK_BUTTON_BACKGROUND_COLOR_ACTIVE: "var(--dark-gray2)",
  DARK_BUTTON_BACKGROUND_COLOR_DISABLED: "hsla(var(--dark-gray5-hsl),0.5)",
  DARK_BUTTON_BACKGROUND_COLOR_ACTIVE_DISABLED: "hsla(var(--dark-gray5-hsl),0.7)",
  DARK_BUTTON_INTENT_COLOR_DISABLED: "hsla(var(--white-hsl),0.3)",
  MINIMAL_BUTTON_BACKGROUND_OPACITY: "0.3",
  MINIMAL_BUTTON_DIVIDER_WIDTH: "1px",
  MINIMAL_BUTTON_BACKGROUND_COLOR: "none",
  MINIMAL_BUTTON_BACKGROUND_COLOR_HOVER: "hsla(var(--gray4-hsl),var(--minimal-button-background-opacity))",
  MINIMAL_BUTTON_BACKGROUND_COLOR_ACTIVE: "hsla(var(--gray2-hsl),var(--minimal-button-background-opacity))",
  DARK_MINIMAL_BUTTON_BACKGROUND_COLOR: "none",
  DARK_MINIMAL_BUTTON_BACKGROUND_COLOR_HOVER: "hsla(var(--gray5-hsl),var(--minimal-button-background-opacity))",
  DARK_MINIMAL_BUTTON_BACKGROUND_COLOR_ACTIVE: "hsla(var(--gray3-hsl),var(--minimal-button-background-opacity))",
  BUTTON_OUTLINED_WIDTH: "1px",
  BUTTON_OUTLINED_BORDER_INTENT_OPACITY: "0.6",
  BUTTON_OUTLINED_BORDER_DISABLED_INTENT_OPACITY: "0.2",
  CARD_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DARK_CARD_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  DIALOG_BORDER_RADIUS: "calc(var(--pt-border-radius)*2)",
  STEP_RADIUS: "calc(var(--pt-border-radius)*2)",
  DRAWER_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DARK_DRAWER_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  INPUT_COLOR: "var(--pt-text-color)",
  INPUT_COLOR_DISABLED: "var(--button-color-disabled)",
  INPUT_PLACEHOLDER_COLOR: "var(--pt-text-color-disabled)",
  INPUT_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  INPUT_BACKGROUND_COLOR_DISABLED: "hsla(var(--light-gray1-hsl),0.5)",
  INPUT_SHADOW_COLOR_FOCUS: "var(--pt-intent-primary)",
  INPUT_SHADOW_COLOR_FOCUS_HSL: "var(--blue3-hsl)",
  DARK_INPUT_COLOR: "var(--pt-dark-text-color)",
  DARK_INPUT_COLOR_DISABLED: "var(--dark-button-color-disabled)",
  DARK_INPUT_PLACEHOLDER_COLOR: "var(--pt-dark-text-color-disabled)",
  DARK_INPUT_BACKGROUND_COLOR: "hsla(var(--black-hsl),0.3)",
  DARK_INPUT_BACKGROUND_COLOR_DISABLED: "hsla(var(--dark-gray5-hsl),0.5)",
  DARK_INPUT_SHADOW_COLOR_FOCUS: "var(--pt-intent-primary)",
  DARK_INPUT_SHADOW_COLOR_FOCUS_HSL: "var(--blue3-hsl)",
  INPUT_BOX_SHADOW_FOCUS: "inset 0 1px 1px hsla(var(--pt-shadow-color-hsl),var(--pt-drop-shadow-opacity))",
  CONTROL_BACKGROUND_COLOR: "var(--button-background-color)",
  CONTROL_BACKGROUND_COLOR_HOVER: "var(--button-background-color-hover)",
  CONTROL_BACKGROUND_COLOR_ACTIVE: "var(--button-background-color-active)",
  DARK_CONTROL_BACKGROUND_COLOR: "var(--dark-button-background-color)",
  DARK_CONTROL_BACKGROUND_COLOR_HOVER: "var(--dark-button-background-color-hover)",
  DARK_CONTROL_BACKGROUND_COLOR_ACTIVE: "var(--dark-button-background-color-active)",
  CONTROL_CHECKED_BACKGROUND_COLOR: "var(--pt-intent-primary)",
  CONTROL_CHECKED_BACKGROUND_COLOR_HOVER: "var(--pt-intent-primary-hover)",
  CONTROL_CHECKED_BACKGROUND_COLOR_ACTIVE: "var(--pt-intent-primary-active)",
  CONTROL_CHECKED_BACKGROUND_COLOR_HSL: "var(--pt-intent-primary-hsl)",
  CONTROL_CHECKED_BACKGROUND_COLOR_HOVER_HSL: "var(--pt-intent-primary-hover-hsl)",
  CONTROL_CHECKED_BACKGROUND_COLOR_ACTIVE_HSL: "var(--pt-intent-primary-active-hsl)",
  SWITCH_BACKGROUND_COLOR: "hsla(var(--gray4-hsl),0.5)",
  SWITCH_BACKGROUND_COLOR_HOVER: "hsla(var(--gray2-hsl),0.5)",
  SWITCH_BACKGROUND_COLOR_ACTIVE: "hsla(var(--gray1-hsl),0.5)",
  SWITCH_BACKGROUND_COLOR_DISABLED: "var(--button-background-color-disabled)",
  SWITCH_CHECKED_BACKGROUND_COLOR: "var(--control-checked-background-color)",
  SWITCH_CHECKED_BACKGROUND_COLOR_HOVER: "var(--control-checked-background-color-hover)",
  SWITCH_CHECKED_BACKGROUND_COLOR_ACTIVE: "var(--control-checked-background-color-active)",
  SWITCH_CHECKED_BACKGROUND_COLOR_DISABLED: "hsla(var(--blue3-hsl),0.5)",
  DARK_SWITCH_BACKGROUND_COLOR: "hsla(var(--black-hsl),0.5)",
  DARK_SWITCH_BACKGROUND_COLOR_HOVER: "hsla(var(--black-hsl),0.7)",
  DARK_SWITCH_BACKGROUND_COLOR_ACTIVE: "hsla(var(--black-hsl),0.9)",
  DARK_SWITCH_BACKGROUND_COLOR_DISABLED: "var(--dark-button-background-color-disabled)",
  DARK_SWITCH_CHECKED_BACKGROUND_COLOR: "var(--control-checked-background-color)",
  DARK_SWITCH_CHECKED_BACKGROUND_COLOR_HOVER: "var(--control-checked-background-color-hover)",
  DARK_SWITCH_CHECKED_BACKGROUND_COLOR_ACTIVE: "var(--control-checked-background-color-active)",
  DARK_SWITCH_CHECKED_BACKGROUND_COLOR_DISABLED: "hsla(var(--blue1-hsl),0.5)",
  SWITCH_INDICATOR_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  SWITCH_INDICATOR_BACKGROUND_COLOR_DISABLED: "hsla(var(--white-hsl),0.8)",
  DARK_SWITCH_INDICATOR_BACKGROUND_COLOR: "var(--dark-gray5)",
  DARK_SWITCH_INDICATOR_BACKGROUND_COLOR_DISABLED: "hsla(var(--black-hsl),0.4)",
  TABLE_BORDER_COLOR: "var(--pt-divider-black)",
  DARK_TABLE_BORDER_COLOR: "var(--pt-dark-divider-white)",
  MENU_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DARK_MENU_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  MENU_ITEM_COLOR_HOVER: "var(--minimal-button-background-color-hover)",
  MENU_ITEM_COLOR_ACTIVE: "var(--minimal-button-background-color-active)",
  DARK_MENU_ITEM_COLOR_HOVER: "var(--dark-minimal-button-background-color-hover)",
  DARK_MENU_ITEM_COLOR_ACTIVE: "var(--dark-minimal-button-background-color-active)",
  NAVBAR_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DARK_NAVBAR_BACKGROUND_COLOR: "var(--dark-gray5)",
  OVERLAY_BACKGROUND_OPACITY: "0.7",
  OVERLAY_BACKGROUND_COLOR: "hsla(var(--black-hsl),var(--overlay-background-opacity))",
  POPOVER_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DARK_POPOVER_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  PROGRESS_TRACK_COLOR: "hsla(var(--gray1-hsl),0.2)",
  PROGRESS_HEAD_COLOR: "hsla(var(--gray1-hsl),0.8)",
  DARK_PROGRESS_TRACK_COLOR: "hsla(var(--black-hsl),0.5)",
  DARK_PROGRESS_HEAD_COLOR: "var(--gray3)",
  PROGRESS_BAR_STRIPES_COLOR: "hsla(var(--white-hsl),0.2)",
  PROGRESS_BAR_GRADIENT: "linear-gradient(-45deg,var(--progress-bar-stripes-color) 25%,transparent 0,transparent 50%,var(--progress-bar-stripes-color) 0,var(--progress-bar-stripes-color) 75%,transparent 0)",
  SKELETON_COLOR_START: "hsla(var(--light-gray1-hsl),0.2)",
  SKELETON_COLOR_END: "hsla(var(--gray1-hsl),0.2)",
  TAB_COLOR_SELECTED: "var(--pt-link-color)",
  DARK_TAB_COLOR_SELECTED: "var(--pt-dark-link-color)",
  TAG_DEFAULT_COLOR: "var(--gray1)",
  DARK_TAG_DEFAULT_COLOR: "var(--gray5)",
  TAG_DEFAULT_COLOR_HSL: "var(--gray1-hsl)",
  DARK_TAG_DEFAULT_COLOR_HSL: "var(--gray5-hsl)",
  TOOLTIP_BACKGROUND_COLOR: "var(--dark-gray5)",
  TOOLTIP_TEXT_COLOR: "var(--light-gray5)",
  DARK_TOOLTIP_BACKGROUND_COLOR: "var(--light-gray3)",
  DARK_TOOLTIP_TEXT_COLOR: "var(--dark-gray5)"
};

export const Datetime = {
  DATEPICKER_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  DATEPICKER_DAY_BACKGROUND_COLOR_HOVER: "var(--light-gray2)",
  DATEPICKER_DAY_BACKGROUND_COLOR_ACTIVE: "var(--light-gray1)",
  DARK_DATEPICKER_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  DARK_DATEPICKER_DAY_BACKGROUND_COLOR_HOVER: "var(--gray1)",
  DARK_DATEPICKER_DAY_BACKGROUND_COLOR_ACTIVE: "var(--gray2)",
  DATERANGEPICKER_RANGE_BACKGROUND_COLOR: "var(--light-gray4)",
  DATERANGEPICKER_RANGE_BACKGROUND_COLOR_SELECTED: "var(--light-gray4)",
  DATERANGEPICKER_RANGE_BACKGROUND_COLOR_SELECTED_HOVER: "var(--light-gray1)",
  DARK_DATERANGEPICKER_RANGE_BACKGROUND_COLOR: "var(--dark-gray5)",
  DARK_DATERANGEPICKER_RANGE_BACKGROUND_COLOR_SELECTED: "var(--dark-gray5)",
  DARK_DATERANGEPICKER_RANGE_BACKGROUND_COLOR_SELECTED_HOVER: "var(--gray1)"
};

export const Table = {
  CELL_BACKGROUND_COLOR: "var(--pt-app-top-background-color)",
  CELL_BACKGROUND_COLOR_OPACITY: "0.1",
  CELL_BORDER_COLOR: "var(--pt-divider-black)",
  CELL_TEXT_COLOR: "var(--pt-text-color)",
  DARK_CELL_BACKGROUND_COLOR: "var(--dark-gray3)",
  DARK_CELL_BORDER_COLOR: "var(--pt-dark-divider-black)",
  DARK_CELL_TEXT_COLOR: "var(--pt-dark-text-color)",
  TABLE_BACKGROUND_COLOR: "var(--light-gray5)",
  DARK_TABLE_BACKGROUND_COLOR: "var(--pt-dark-app-top-background-color)",
  TABLE_BACKGROUND_COLOR_HSL: "var(--light-gray5-hsl)",
  DARK_TABLE_BACKGROUND_COLOR_HSL: "var(--pt-dark-app-top-background-color-hsl)",
  HEADER_BACKGROUND_COLOR: "var(--table-background-color)",
  HEADER_HOVER_BACKGROUND_COLOR: "var(--light-gray3)",
  COLUMN_HEADER_TEXT_COLOR: "var(--pt-text-color)",
  ROW_HEADER_TEXT_COLOR: "var(--pt-text-color-muted)",
  DARK_HEADER_BACKGROUND_COLOR: "var(--dark-table-background-color)",
  DARK_HEADER_HOVER_BACKGROUND_COLOR: "var(--dark-gray5)",
  DARK_COLUMN_HEADER_TEXT_COLOR: "var(--pt-dark-text-color)",
  DARK_ROW_HEADER_TEXT_COLOR: "var(--pt-dark-text-color-muted)",
  HEADER_SELECTED_BACKGROUND_COLOR: "var(--pt-intent-primary)",
  HEADER_BACKGROUND_COLOR_HSL: "var(--table-background-color-hsl)",
  HEADER_HOVER_BACKGROUND_COLOR_HSL: "var(--light-gray3-hsl)",
  HEADER_SELECTED_BACKGROUND_COLOR_HSL: "var(--pt-intent-primary-hsl)",
  HEADER_SELECTED_HOVER_BACKGROUND_COLOR_HSL: "var(--pt-intent-primary-hue),40%,91%",
  COLUMN_HEADER_TEXT_COLOR_HSL: "var(--pt-text-color)",
  ROW_HEADER_TEXT_COLOR_HSL: "var(--pt-text-color-muted)",
  DARK_HEADER_BACKGROUND_COLOR_HSL: "var(--dark-table-background-color-hsl)",
  DARK_HEADER_HOVER_BACKGROUND_COLOR_HSL: "var(--dark-gray5-hsl)",
  DARK_HEADER_SELECTED_BACKGROUND_COLOR_HSL: "var(--pt-intent-primary-hue),40%,25%",
  DARK_HEADER_SELECTED_HOVER_BACKGROUND_COLOR_HSL: "var(--pt-intent-primary-hue),40%,29%",
  DARK_COLUMN_HEADER_TEXT_COLOR_HSL: "var(--pt-dark-text-color)",
  DARK_ROW_HEADER_TEXT_COLOR_HSL: "var(--pt-dark-text-color-muted)",
  RESIZE_HANDLE_COLOR: "var(--pt-intent-primary)",
  RESIZE_HANDLE_DRAGGING_COLOR: "var(--pt-intent-primary)",
  REGION_DEFAULT_COLOR: "var(--gray3)",
  REGION_SELECTED_COLOR: "var(--pt-intent-primary)",
  REGION_DEFAULT_COLOR_HSL: "var(--gray3-hsl)",
  REGION_SELECTED_COLOR_HSL: "var(--pt-intent-primary-hsl)"
};
