
exports.ColorsHsl = {
	BlackHsl: "var(--black-hsl)",
	DarkGray1Hsl: "var(--dark-gray1-hsl)",
	DarkGray2Hsl: "var(--dark-gray2-hsl)",
	DarkGray3Hsl: "var(--dark-gray3-hsl)",
	DarkGray4Hsl: "var(--dark-gray4-hsl)",
	DarkGray5Hsl: "var(--dark-gray5-hsl)",
	Gray1Hsl: "var(--gray1-hsl)",
	Gray2Hsl: "var(--gray2-hsl)",
	Gray3Hsl: "var(--gray3-hsl)",
	Gray4Hsl: "var(--gray4-hsl)",
	Gray5Hsl: "var(--gray5-hsl)",
	LightGray1Hsl: "var(--light-gray1-hsl)",
	LightGray2Hsl: "var(--light-gray2-hsl)",
	LightGray3Hsl: "var(--light-gray3-hsl)",
	LightGray4Hsl: "var(--light-gray4-hsl)",
	LightGray5Hsl: "var(--light-gray5-hsl)",
	WhiteHsl: "var(--white-hsl)",
	Cerulean1Hsl: "var(--cerulean1-hsl)",
	Cerulean2Hsl: "var(--cerulean2-hsl)",
	Cerulean3Hsl: "var(--cerulean3-hsl)",
	Cerulean4Hsl: "var(--cerulean4-hsl)",
	Cerulean5Hsl: "var(--cerulean5-hsl)",
	Green1Hsl: "var(--green1-hsl)",
	Green2Hsl: "var(--green2-hsl)",
	Green3Hsl: "var(--green3-hsl)",
	Green4Hsl: "var(--green4-hsl)",
	Green5Hsl: "var(--green5-hsl)",
	Orange1Hsl: "var(--orange1-hsl)",
	Orange2Hsl: "var(--orange2-hsl)",
	Orange3Hsl: "var(--orange3-hsl)",
	Orange4Hsl: "var(--orange4-hsl)",
	Orange5Hsl: "var(--orange5-hsl)",
	Red1Hsl: "var(--red1-hsl)",
	Red2Hsl: "var(--red2-hsl)",
	Red3Hsl: "var(--red3-hsl)",
	Red4Hsl: "var(--red4-hsl)",
	Red5Hsl: "var(--red5-hsl)",
	Cerulean6Hsl: "var(--cerulean6-hsl)",
	Green6Hsl: "var(--green6-hsl)",
	Orange6Hsl: "var(--orange6-hsl)",
	Red6Hsl: "var(--red6-hsl)",
	Vermilion1Hsl: "var(--vermilion1-hsl)",
	Vermilion2Hsl: "var(--vermilion2-hsl)",
	Vermilion3Hsl: "var(--vermilion3-hsl)",
	Vermilion4Hsl: "var(--vermilion4-hsl)",
	Vermilion5Hsl: "var(--vermilion5-hsl)",
	Rose1Hsl: "var(--rose1-hsl)",
	Rose2Hsl: "var(--rose2-hsl)",
	Rose3Hsl: "var(--rose3-hsl)",
	Rose4Hsl: "var(--rose4-hsl)",
	Rose5Hsl: "var(--rose5-hsl)",
	Violet1Hsl: "var(--violet1-hsl)",
	Violet2Hsl: "var(--violet2-hsl)",
	Violet3Hsl: "var(--violet3-hsl)",
	Violet4Hsl: "var(--violet4-hsl)",
	Violet5Hsl: "var(--violet5-hsl)",
	Indigo1Hsl: "var(--indigo1-hsl)",
	Indigo2Hsl: "var(--indigo2-hsl)",
	Indigo3Hsl: "var(--indigo3-hsl)",
	Indigo4Hsl: "var(--indigo4-hsl)",
	Indigo5Hsl: "var(--indigo5-hsl)",
	Blue1Hsl: "var(--blue1-hsl)",
	Blue2Hsl: "var(--blue2-hsl)",
	Blue3Hsl: "var(--blue3-hsl)",
	Blue4Hsl: "var(--blue4-hsl)",
	Blue5Hsl: "var(--blue5-hsl)",
	Turquoise1Hsl: "var(--turquoise1-hsl)",
	Turquoise2Hsl: "var(--turquoise2-hsl)",
	Turquoise3Hsl: "var(--turquoise3-hsl)",
	Turquoise4Hsl: "var(--turquoise4-hsl)",
	Turquoise5Hsl: "var(--turquoise5-hsl)",
	Forest1Hsl: "var(--forest1-hsl)",
	Forest2Hsl: "var(--forest2-hsl)",
	Forest3Hsl: "var(--forest3-hsl)",
	Forest4Hsl: "var(--forest4-hsl)",
	Forest5Hsl: "var(--forest5-hsl)",
	Lime1Hsl: "var(--lime1-hsl)",
	Lime2Hsl: "var(--lime2-hsl)",
	Lime3Hsl: "var(--lime3-hsl)",
	Lime4Hsl: "var(--lime4-hsl)",
	Lime5Hsl: "var(--lime5-hsl)",
	Gold1Hsl: "var(--gold1-hsl)",
	Gold2Hsl: "var(--gold2-hsl)",
	Gold3Hsl: "var(--gold3-hsl)",
	Gold4Hsl: "var(--gold4-hsl)",
	Gold5Hsl: "var(--gold5-hsl)",
	Sepia1Hsl: "var(--sepia1-hsl)",
	Sepia2Hsl: "var(--sepia2-hsl)",
	Sepia3Hsl: "var(--sepia3-hsl)",
	Sepia4Hsl: "var(--sepia4-hsl)",
	Sepia5Hsl: "var(--sepia5-hsl)",
};

exports.Variables = {
	PtInputBoxShadow: "var(--pt-input-box-shadow)",
};

exports.IntentColors = {
	Primary1Hsl: "var(--primary1-hsl)",
	Primary2Hsl: "var(--primary2-hsl)",
	Primary3Hsl: "var(--primary3-hsl)",
	Primary4Hsl: "var(--primary4-hsl)",
	Primary5Hsl: "var(--primary5-hsl)",
	Primary6Hsl: "var(--primary6-hsl)",
};

exports.Components = {
	ButtonBoxShadow: "var(--button-box-shadow)",
	ButtonBoxShadowActive: "var(--button-box-shadow-active)",
	ButtonGradient: "var(--button-gradient)",
	ButtonIntentGradient: "var(--button-intent-gradient)",
	MinimalButtonBackgroundColorHover: "var(--minimal-button-background-color-hover)",
	MinimalButtonBackgroundColorActive: "var(--minimal-button-background-color-active)",
};
